### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/iAuditor_Toolkit#23]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] iAuditor_Toolkit\iAuditor_Engine\Create\iAuditorRequest.cs

</p>
</details>

**Comment by enarhi** [comment]
As noted in https://github.com/BHoM/OpenStreetMap_Toolkit/issues/50 this CustomData is a result of parsing custom objects and will be resolved separately once the corresponding BHoM issue is resolved and an alternate name for this data is chosen.

**Comment by FraserGreenroyd** [comment]
Since determined not to rename custom data is usage in this toolkit is valid.
