### ISSUE TITLE
Review https://github.com/BHoM/iAuditor_Toolkit/pull/39

### ISSUE THREAD

**Issue by adecler** [BHoM/iAuditor_Toolkit#40]
https://github.com/BHoM/iAuditor_Toolkit/pull/39 had to be merge to allow the master to compile again. 

The code on that PR still need proper review though.

If any change is required, please create a new PR with the corrections.

**Comment by tiagogrossi** [comment]
@adecler thanks for this. I can confirm that I just tested PR #39 and it works as expected now. No further actions required.
